---
title: fluxible download logs
author: Joseph Gaudard
date: today
format: gfm
---

```{r}
#| label: packages
#| include: false
#| message: false

library(tidyverse)
library(adjustedcranlogs)
library(zoo)

date_end <- today() - 2
```

```{r}
#| label: fig-lastmonth
#| echo: false
#| fig-cap: "Number of downloads for the last month."
#| fig-height: 6
#| fig-width: 10
#| message: false
#| warning: false

adj_cran_downloads(c("fluxible", "fluxfinder", "gasfluxes", "flux", "HMR", "licoread"), "last-month") |>
  pivot_longer(c(adjusted_downloads, adjusted_total_downloads)) |>
  ggplot(aes(date, value, color = package)) +
  geom_line(aes(alpha = package), linewidth = 0.6) +
  theme_bw() +
  facet_grid(name ~ ., scales = "free") +
  scale_alpha_manual(values = c(rep(0.5, 2), 1, rep(0.5, 3))) +
  labs(
    title = "Last month"
  ) +
  scale_x_date(date_minor_breaks = "1 day")

```

```{r}
#| label: fig-paper
#| echo: false
#| fig-cap: "Number of downloads since paper was published."
#| fig-height: 8
#| fig-width: 10
#| message: false
#| warning: false

adj_cran_downloads(c("fluxible", "fluxfinder", "gasfluxes", "flux", "HMR", "licoread"), from = "2025-09-24", to = date_end) |>
  mutate(
    rollmean_5days = rollmean(adjusted_downloads, 5, fill = NA, align = "right"),
    .by = package
  ) |>
  pivot_longer(c(adjusted_downloads, adjusted_total_downloads, rollmean_5days)) |>
  ggplot(aes(date, value, color = package)) +
  geom_line(aes(alpha = package), linewidth = 0.6) +
  theme_bw() +
  facet_grid(name ~ ., scales = "free") +
  scale_alpha_manual(values = c(rep(0.5, 2), 1, rep(0.5, 3))) +
  labs(
    title = "Since paper publication"
  ) +
  scale_x_date(date_breaks = "5 days", limits = c(ymd("2025-09-24"), NA), date_minor_breaks = "1 day")

```

```{r}
#| label: fig-overall
#| echo: false
#| fig-cap: "Overall number of downloads since first CRAN acceptance."
#| fig-height: 8
#| fig-width: 10
#| message: false
#| warning: false


adj_cran_downloads(c("fluxible", "fluxfinder", "gasfluxes", "flux", "HMR", "licoread"), from = "2024-08-27", to = date_end) |>
  mutate(
    rollmean_10days = rollmean(adjusted_downloads, 10, fill = NA, align = "right"),
    .by = package
  ) |>
  pivot_longer(c(adjusted_downloads, adjusted_total_downloads, rollmean_10days)) |>
  ggplot(aes(date, value, color = package)) +
  geom_line(aes(alpha = package), linewidth = 0.6) +
  theme_bw() +
  facet_grid(name ~ ., scales = "free") +
  scale_alpha_manual(values = c(rep(0.5, 2), 1, rep(0.5, 3))) +
  # scale_linewidth_manual(values = c(rep(0.4, 2), 1, rep(0.4, 3))) +
  labs(
    title = "Since first CRAN acceptance"
  ) +
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "5 days")

```